1 在方法中，如果抛出异常，且没有被捕获，则程序报错并中断执行

2 如果在方法外（声明方法处）通过throw提前抛出异常，则此方法中断执行，异常向上抛出，如果上层没有捕获此异常，则同（1）

3 如果上层方法通过try catch捕获了此异常，则程序继续执行,且执行catch中的逻辑，但是顺序无法保证                                       
